name: Clean Sensitive Data

on:
  workflow_dispatch:

jobs:
  scan-and-clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "josiasndam22@gmail.com"
        git config --global user.name "jndamito"

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install BFG Repo-Cleaner
      run: wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar -O bfg.jar

    - name: Install Gitleaks
      run: |
        git clone https://github.com/gitleaks/gitleaks.git
        cd gitleaks
        make build
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Gitleaks scan
      run: gitleaks detect --source . --report-format json --report-path gitleaks_report.json --verbose
      continue-on-error: true

    - name: Replace secrets in commit history
      run: |
        python3 - <<'EOF'
        import json

        def create_replacements_file(input_file, output_file):
            with open(input_file, 'r') as infile:
                data = json.load(infile)

            replacements = []
            for finding in data:
                secret = finding.get('Secret')
                if secret:
                    if 'AWS' in secret:
                        placeholder = '[SENSITIVE_DATA_AWS_KEY]'
                    elif 'API' in secret:
                        placeholder = '[SENSITIVE_DATA_API_KEY]'
                    elif 'Azure' in secret:
                        placeholder = '[SENSITIVE_DATA_AZURE_KEY]'
                    else:
                        placeholder = '[SENSITIVE_DATA]'
                    replacements.append(f'{secret}==>{placeholder}')

            with open(output_file, 'w') as outfile:
                outfile.write('\n'.join(replacements))

        create_replacements_file('gitleaks_report.json', 'replacements.txt')
        EOF

    - name: Replace secrets in files
      run: |
        python3 - <<'EOF'
        import json
        import os

        def replace_secrets(input_file):
            with open(input_file, 'r') as infile:
                data = json.load(infile)

            replacements = {}
            for finding in data:
                secret = finding.get('Secret')
                if secret:
                    if 'AWS' in secret:
                        placeholder = '[SENSITIVE_DATA_AWS_KEY]'
                    elif 'API' in secret:
                        placeholder = '[SENSITIVE_DATA_API_KEY]'
                    elif 'Azure' in secret:
                        placeholder = '[SENSITIVE_DATA_AZURE_KEY]'
                    else:
                        placeholder = '[SENSITIVE_DATA]'
                    replacements[secret] = placeholder

            modified_files = set()
            for root, _, files in os.walk('.'):
                for file in files:
                    file_path = os.path.join(root, file)
                    try:
                        with open(file_path, 'r', encoding='utf-8') as f:
                            content = f.read()
                        new_content = content
                        for secret, placeholder in replacements.items():
                            new_content = new_content.replace(secret, placeholder)
                        if new_content != content:
                            with open(file_path, 'w', encoding='utf-8') as f:
                                f.write(new_content)
                            modified_files.add(file_path)
                    except UnicodeDecodeError:
                        print(f"Skipping file due to encoding error: {file_path}")

            with open('modified_files.txt', 'w') as f:
                f.write('\n'.join(modified_files))

        replace_secrets('gitleaks_report.json')
        EOF

    - name: Commit changes
      run: |
        cat modified_files.txt | xargs git add
        git commit -m "Replace secrets with placeholders"
        continue-on-error: true

    - name: Replace sensitive data with BFG Repo-Cleaner
      run: java -jar bfg.jar --replace-text replacements.txt

    - name: Cleanup and force push
      run: |
        git reflog expire --expire=now --all
        git gc --prune=now --aggressive
        git push --force

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v2
      with:
        name: gitleaks-report
        path: gitleaks_report.json
